AWSTemplateFormatVersion: 2010-09-09
Description: Automatic creation of an Item in DynamoDB
Parameters:
  CustomDynDBOnboardArn:
    Type: String
    Description: The ARN of the custom resource creating DynamoDB items automatically
  VpcId:
    Type: String
  EktName:
    Type: String
    Default: ''
  RoleArn:
    Type: String
    Default: ''
  AuditBucketName:
    Type: String
    Default: ''

Conditions:
  bWithEktName: !Not [ !Equals [ !Ref EktName, '' ] ]
  bWithRoleArn: !Not [ !Equals [ !Ref RoleArn, '' ] ]
  bWithAuditBucketName: !Not [ !Equals [ !Ref AuditBucketName, '' ] ]

Resources:
  CustomDynDBOnboard:
     Type: Custom::CustomDynDBOnboard
     Properties:
       ServiceToken: !Ref CustomDynDBOnboardArn
       VpcId: !Ref VpcId
       EktName: !If [ bWithEktName, !Ref EktName, !Ref AWS::NoValue ]
       RemoteRoleARN: !If [ bWithRoleArn, !Ref RoleArn, !Ref AWS::NoValue ]
       AuditBucketName: !If [ bWithAuditBucketName, !Ref AuditBucketName, !Ref AWS::NoValue ]
